"""Gifts API — the user-facing "digital gifts" view.

A digital gift is a small warm thing Sandy makes — a poem, a quote, a pep
message, a smile, a joke, a riddle — kept for a recipient and an occasion, and
optionally scheduled for a date. This is the keep/schedule layer; the content
itself is generated by the same helper the agent's `digital_gift` tool uses
(`app.agent.tools.schemas.gift_tools._generate_with_llm`).

Telegram decoupling: the legacy gift flow used to *deliver* a gift over
Telegram. That delivery path is gone — `digital_gift` now only returns text and
the tool keeps no store of its own. So this API persists gifts purely over REST
in Mongo (no Telegram, no chat-id delivery). A scheduled gift simply carries a
`scheduled_at` date the app surfaces; nothing pushes it out a Telegram channel.

Each gift is one plain doc in `sandy_gifts`, scoped to the caller's own
``user_id`` (isolated; guests get nothing). Fields:
  chat_id      owner's user_id (the active-profile scope key)
  kind         one of poem|quote|motivation|smile|joke|riddle
  recipient    free text — who it's for
  occasion     free text — the occasion
  content      the generated/written gift text (optional)
  scheduled_at ISO date string or "" (optional — "" = saved, not scheduled)
  created_at   server timestamp

Endpoints:
  GET    /api/gifts            this user's saved + scheduled gifts
  POST   /api/gifts            keep a new gift (optionally scheduled)
  POST   /api/gifts/generate   ask Sandy to write a gift idea (no persistence)
  DELETE /api/gifts/<gift_id>  remove one gift
"""

from __future__ import annotations

from flask import jsonify, request

from app.api.auth_handlers import require_auth
from app.utils.user_profiles import (
    active_user_profile_context,
    build_user_profile,
    current_user_id,
)

# The gift kinds Sandy can write — mirrors the agent tool's enum exactly so the
# generation helper recognizes them.
_GIFT_KINDS = {"poem", "quote", "motivation", "smile", "joke", "riddle"}


def _clean_kind(value) -> str:
    kind = str(value or "smile").strip().lower()
    return kind if kind in _GIFT_KINDS else "smile"


def register_gifts_api(app, mongo_db=None):
    @app.route("/api/gifts", methods=["GET"])
    @require_auth
    def get_gifts(claims):
        if mongo_db is None:
            return jsonify({"items": []}), 200
        with active_user_profile_context(build_user_profile(claims)):
            uid = current_user_id()
            if not uid:
                return jsonify({"items": []}), 200
            items = []
            cur = (
                mongo_db["sandy_gifts"]
                .find({"chat_id": uid})
                .sort("created_at", -1)
                .limit(300)
            )
            for d in cur:
                items.append({
                    "id": str(d["_id"]),
                    "kind": d.get("kind", "smile"),
                    "recipient": d.get("recipient", ""),
                    "occasion": d.get("occasion", ""),
                    "content": d.get("content", ""),
                    "scheduled_at": d.get("scheduled_at", ""),
                })
        return jsonify({"items": items}), 200

    @app.route("/api/gifts", methods=["POST"])
    @require_auth
    def add_gift(claims):
        if mongo_db is None:
            return jsonify({"ok": False}), 200
        body = request.get_json(silent=True) or {}
        recipient = (body.get("recipient") or "").strip()
        occasion = (body.get("occasion") or "").strip()
        if not recipient or not occasion:
            return jsonify({"error": "recipient_and_occasion_required"}), 400
        from datetime import datetime, timezone

        with active_user_profile_context(build_user_profile(claims)):
            uid = current_user_id()
            if not uid:
                return jsonify({"ok": False}), 403
            res = mongo_db["sandy_gifts"].insert_one({
                "chat_id": uid,
                "kind": _clean_kind(body.get("kind")),
                "recipient": recipient,
                "occasion": occasion,
                "content": (body.get("content") or "").strip(),
                "scheduled_at": (body.get("scheduled_at") or "").strip(),
                "created_at": datetime.now(timezone.utc),
            })
        return jsonify({"ok": True, "id": str(res.inserted_id)}), 200

    @app.route("/api/gifts/generate", methods=["POST"])
    @require_auth
    def generate_gift(claims):
        """Ask Sandy to write a gift idea — reuses the agent tool's LLM helper.

        Stateless: it only returns text; nothing is persisted. The client may
        send that text back to POST /api/gifts to keep it.
        """
        body = request.get_json(silent=True) or {}
        kind = _clean_kind(body.get("kind"))
        # Context = recipient + occasion, so the generated text fits the moment.
        bits = [
            (body.get("recipient") or "").strip(),
            (body.get("occasion") or "").strip(),
        ]
        context = " — ".join(b for b in bits if b)
        # Scope is enforced even though we don't read a store: a guest profile
        # without a user_id is fail-closed below.
        with active_user_profile_context(build_user_profile(claims)):
            if not current_user_id():
                return jsonify({"content": ""}), 403
            from app.agent.tools.schemas.gift_tools import _generate_with_llm

            content = _generate_with_llm(kind, context) or ""
        return jsonify({"content": content}), 200

    @app.route("/api/gifts/<gift_id>", methods=["DELETE"])
    @require_auth
    def delete_gift(claims, gift_id):
        if mongo_db is None:
            return jsonify({"ok": False}), 200
        from bson import ObjectId
        from bson.errors import InvalidId

        try:
            oid = ObjectId(gift_id)
        except (InvalidId, TypeError):
            return jsonify({"ok": False}), 200
        with active_user_profile_context(build_user_profile(claims)):
            uid = current_user_id()
            if not uid:
                return jsonify({"ok": False}), 403
            res = mongo_db["sandy_gifts"].delete_one({"_id": oid, "chat_id": uid})
        return jsonify({"ok": res.deleted_count > 0}), 200
