"""Function-calling routing for Sandy.

Builds a compact prompt from the current message, recent context, and any
pending state, then asks the model for structured JSON.

From the picked tool it derives intent and routing_hint, and carries through
mood, persona fields, confidence, and any multi-tool calls. If the model call
fails it tries GPT routing, then falls back to a safe default.
"""

from __future__ import annotations

import json
import logging
import os
import re
import time
from typing import Any, Dict, List, Optional

from app.agent.graph.state import SandyState, merge_state
from app.integrations.azure_intent_client import AzureIntentClient
from app.utils.user_profiles import address_instruction

logger = logging.getLogger(__name__)


def _fast_route_generate(system: str, user_prompt: str) -> "Optional[str]":
    """Routing-only fast path: a lighter model returns the same routing JSON.

    Enabled by ``SANDY_ROUTER_MODEL`` (e.g. ``gpt-4o-mini``) + ``OPENAI_API_KEY``.
    The actual reply is still generated by the full model downstream, so only the
    routing *decision* uses the cheaper model. Returns the raw JSON string, or
    None to fall back to the default Azure router.
    """
    model = os.getenv("SANDY_ROUTER_MODEL", "").strip()
    if not model:
        return None
    try:
        from app.agent.model_fallback import _get_openai_direct_client

        client = _get_openai_direct_client()
        if client is None:
            return None
        resp = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0,
            max_tokens=600,
            response_format={"type": "json_object"},
        )
        return resp.choices[0].message.content
    except Exception as e:  # noqa: BLE001
        logger.warning("[fc_router] fast route failed, falling back: %s", e)
        return None

logger = logging.getLogger(__name__)

# Handled by routing logic, not the ToolDispatcher.
_META_TOOL_NAMES = frozenset({
    "ask_clarification",
    "request_confirmation",
    "chat_respond",
    "chat_emotional",
    "pending_confirm",
    "pending_reject",
    "pending_select",
})

_FC_DEFAULT: Dict[str, Any] = {
    "function_call": {"name": "chat_respond", "args": {"type": "general"}},
    "mood": "neutral",
    "persona_intensity": "standard",
    "persona_snippet": "",
    "confidence": 0.7,
}

_FC_SYSTEM_TEMPLATE = """\
أنت محلل نية لمساعد Sandy. أرجع JSON فقط — لا نص خارجه.

أدوات ثابتة دائماً متاحة:
- chat_respond(type:str) — دردشة عامة أو لا يوجد طلب واضح
- chat_emotional() — دعم عاطفي (stress/frustration/sadness)
- ask_clarification(question:str) — confidence<0.7 في إرسال/تعديل فقط
- request_confirmation(summary:str) — للعمليات الخطيرة فقط عدا task_delete وtask_complete (هم يطلبون تأكيداً تلقائياً)
- pending_confirm() | pending_reject() | pending_select(choice:str) — الرد على pending نشط

قواعد:

🚨 قاعدة عُليا — لها أولوية على أي قاعدة أخرى:

أي رسالة فيها **فعل action + object واضح** → استدعِ الـ FC المخصص حصراً.
ممنوع تماماً chat_respond في هذه الحالات — حتى لو STM فيه محادثة مشابهة.

أفعال الـ action:
- إنشاء: اعملي/اعمليلي/سوّيلي/أنشئي/حطي/حطيلي/ضيفي/أضيفي/افتحي (بدون "من جديد")
- إغلاق: اقفلي/سكّري/بطّلي/أغلقي
- إعادة فتح: افتحي + "من جديد" / reopen / فعّلي
- تعليق: علّقي/ضيفي تعليق
- عرض: جيبيلي/اعرضيلي/اعرضي/وين/كم عندي
- إنشاء صورة: ولّدي/ارسمي/صمّمي + صورة
- تعديل: عدّلي/غيّري/صلّحي
- حذف: احذفي/امسحي/شيلي

Objects شائعة: صورة, task/مهمة, تذكير/reminder, موعد/event.

أمثلة محسومة (case-closed) — احفظها كنماذج تعلّم:

# مجال الصور
- "اعملي صورة لكلب يلعب"             → image_generate (ليس chat)
- "ولّدي صورة منظر طبيعي"            → image_generate
- "ارسميلي logo بسيط"                 → image_generate
- "عدّلي الصورة، شيلي الخلفية"        → image_edit (الـ object = صورة)
- "غيّري لون الصورة"                  → image_edit

# مجال المواعيد — صارت تذكيرات محلية (ما في تقويم خارجي)
- "اعملي موعد بكره الساعة 5"          → reminder_create (ليس image_edit حتى لو فعل "اعملي")
- "غيّري الموعد لبكره"                → reminder_update (الـ object = موعد، ليس صورة!)
- "احذفي الموعد"                       → reminder_delete
- "اعرضي مواعيدي"                     → reminder_list
# ⚠️ صياغات المواعيد الضمنية (بدون فعل صريح) — كلها → reminder_create
- "في عندي مقابلة الأربعاء"           → reminder_create
- "عندي مشوار يوم السبت"              → reminder_create
- "سجّلي عندك إنّي مشغول الإثنين"     → reminder_create (ليس memory_store — هذا حدث زمني)
- "احجزيلي وقت السبت 7"               → reminder_create

# مجال المهام
- "اعملي مهمة اشتري الحليب"           → task_create
- "ضيفي مهمة جديدة"                    → task_create
- 'ضيفي مهمة "ابعتي ايميل لأحمد"'      → task_create (المحتوى داخل "..." اسم المهمة فقط — ليس أمر فعلي)
- "اعرضي مهامي"                        → task_list
- "غيّري المهمة 3 لـ ..."             → task_update
- "خلّصت المهمة 3" / "كملت ..."        → task_complete
- "ارجعي المهمة 3 / خليها مش مكتملة"  → task_uncomplete
- "علّميها لسّى مش مخلّصة"             → task_uncomplete (انتبه لـ "مش"!)
- "احذفي مهامي المكتملة"              → task_delete

# مجال التذكير
- "ذكّريني أشتري حليب بكره"           → reminder_create
- "ضيفي تذكير الساعة 9"               → reminder_create
- "اعرضي تذكيراتي"                     → reminder_list
- "احذفي تذكير اليوم"                  → reminder_delete
# ⚠️ negation — "ما/مش/بطّلي + تذكير" = حذف
- "ما تذكّريني بشي"                    → reminder_delete (ليس chat)
- "بطّلي التذكير"                      → reminder_delete
- "الغي تذكير اليوم"                   → reminder_delete

# مجال البحث والمعلومات
- "ابحثي عن آخر أخبار X"               → research_web
- "وين مطعم قريب؟" / "places حولي"    → research_places
- "شو الطقس اليوم"                    → get_weather
- "كم الساعة"                          → get_time

# مجال الذاكرة
- "احفظي إنّي بحب القهوة"             → memory_store
- "شو تتذكري عني؟"                     → memory_recall

# الـ chat الحقيقي (لا fc)
- "كيفك اليوم؟"                        → chat_respond
- "حدّثيني عن نفسك"                    → chat_respond
- "تصبحي على خير"                      → chat_respond
- "شكراً يا حبيبتي"                    → chat_respond + persona=playful
- "ما عم أعرف شو الصح"                → chat_emotional (إذا mood ضاغط)
# 🚨 التحيات الخالصة دائماً chat_respond — حتى لو STM فيه طلب سابق فشل
- "مرحبا" / "مرحبتين" / "هلا" / "أهلين" / "سلام" / "السلام عليكم" → chat_respond
- "صباح الخير" / "مساء الخير" / "مساء النور"                       → chat_respond
- ❌ ممنوع تستخدم STM لاستنتاج "المستخدم يبي يكمل الطلب السابق" من تحية فقط

# 🎯 حالات الالتباس الشائعة (cross-domain)
- "غيّري الموعد" (object=موعد)         → reminder_update (ليس image_edit)
- "غيّري الصورة" (object=صورة)         → image_edit (ليس reminder_update)
- "احذفي المهمة"                       → task_delete (ليس reminder_delete)
- "احذفي الموعد"                       → reminder_delete (ليس task_delete)
- "اعملي صورة" (object=صورة)           → image_generate (ليس chat)

🔴 ممنوعات صريحة:
- ❌ chat_respond إذا الرسالة action+object
- ❌ تخطّي الـ FC بحجة "حكينا عنه قبل قليل" — STM قديم بطبيعته
- ❌ افتراض إن الحالة ما تغيّرت — الـ handler يفحص live من DB
- ❌ image_edit إذا الـ object هو task (مش صورة)
- ❌ research_web إذا في FC مخصص للموضوع
- ❌ **إعادة طلب من STM**: لو الرسالة الحالية تحية/شات عام، ممنوع تستدعي FC بحجة "المستخدم يبي يكمل طلب سابق فشل". الرسالة الحالية حصراً.
- ❌ **multi-FC من STM**: ممنوع تجمع function_calls من رسالة سابقة + رسالة حالية. كل رسالة في STM **نُفّذت سابقاً** — حتى لو الرسالة الحالية تبدأ بـ "و" (واو عاطفة) فهي طلب جديد مستقل، مش استكمال.

⚠️ ask_clarification — استخدم بحذر شديد، فقط في حالة غموض كامل:

✅ يُستخدم فقط لما:
- الـ object غير موجود تماماً: "احذفي"، "اعملي"، "غيّري" بدون أي تكملة
- الـ object غامض جداً: "اعملي حاجة"، "ضيفيلي شي"

❌ ممنوع ask_clarification في الحالات التالية — استدعِ الـ FC مباشرةً:
- الـ object واضح حتى لو التفاصيل ناقصة:
  • "احذفي الموعد" → reminder_delete (الـ handler يسأل أي موعد)
  • "غيّري المهمة 3" → task_update (الـ handler يسأل عن التغيير)
  • "اعملي موعد بكره" → reminder_create (الـ handler يكمل التفاصيل)
  • "احذفي التذكير" → reminder_delete (الـ handler يحدد)
  • "غيّري الصورة" → image_edit (الـ handler يسأل التعديل المطلوب)
- التفاصيل ناقصة لكن النية واضحة → نادِ الـ FC، الـ handler يحل التفاصيل
- الرسالة فيها فعل + object → القاعدة العليا (FC حصرًا)

القاعدة: ask_clarification هي **الملاذ الأخير**، ليست الخيار الأول.

🔴 حالات MUST يستدعي الـ FC، حتى لو بدت ناقصة (لا تستخدم ask_clarification):
- "غيّري الموعد بكره" → reminder_update
- "غيّري الموعد لبكره الساعة 6" → reminder_update
- "ضيفي مهمة جديدة الجمعة" → task_create
- "غيّري الصورة" → image_edit
- "احذفي الموعد" → reminder_delete
- "احذفي التذكير" → reminder_delete

إذا ترددت بين FC وask_clarification → اختر الـ FC دائماً.
الـ handler مصمّم للتعامل مع التفاصيل الناقصة بنفسه.

مسؤوليتك: الاستدعاء الصحيح. التعامل مع التكرار/التفاصيل الناقصة/idempotency: الـ handler.

──────────────────────────────────────────────

- pending_state نشط + رد قصير (تمام/لأ/رقم) → pending_confirm|pending_reject|pending_select
- pending_state نوعه clarification: اعتبر الرسالة الحالية إجابة للسؤال السابق. اقرأ "الرسالة الأصلية للمستخدم" واستنتج الـ FC المناسب، ثم استدعِه مع الرسالة الحالية كمعطى ناقص. أمثلة:
  • أصلية="ضيفي مهمة" + حالية="اشتري حليب" → task_create(title="اشتري حليب")
  ممنوع chat_respond في هذي الحالة.
- task_delete أو task_complete مع all=true → استدعِهم مباشرةً بـ all=true — لا تستخدم request_confirmation
- 'عندي اجتماع/موعد/لقاء/دكتور + وقت أو تاريخ' → reminder_create (ليس reminder_list)
- 'شو عندي/مواعيدي/برنامجي' → reminder_list
- 'ابحث/بحث/وين/شو آخر/أخبار/لوين وصل/شو صار' أو أي سؤال عن أحداث جارية أو معلومات تتغير مع الوقت → research_web (ليس chat_respond)
- ⚠️ جهاز مفرد مقابل مشهد مقابل جلسة (أخطاء شائعة — انتبه):
  • أمر على **جهاز مفرد** ('ضوّي/نوري الضو'، 'طفّي المروحة'، 'افتح الستارة', 'المكيف ٢٢') → device_control. «ضوّي/نوري»=on، «طفّي»=off. device لازم من الأجهزة المسجّلة بالبرومبت؛ ما في جهاز مطابق → استدعِ device_control برضه (بترجّع القائمة وتسأل)، لا تخترع اسم.
  • 'شغّلي وضع/جو X (دراسة/فيلم/راحة...)' = مشهد كامل متعدّد الأجهزة → scene_apply.
  • 'خلصت/وقّفي/ألغي الجلسة أو التركيز أو البومودورو' → focus_stop فقط.
  ❌ ممنوع scene_apply لأمر جهاز مفرد، وممنوع تطبيق مشهد عكس الطلب (إطفاء لمّا يطلب تشغيل).
- لا يوجد طلب واضح → chat_respond
- مزاج ضاغط (stressed/frustrated): persona_intensity=empathetic + persona_snippet كسؤال لطيف (مثل "بدك تاخد نفس؟") — لا توجيه مباشر
- أسئلة فلسفية/وجودية/عن المعنى والحياة والكون → chat_respond + persona_intensity=empathetic
- المستخدم يشكر Sandy أو يثني عليها → chat_respond + persona_intensity=playful
- **الرسالة الحالية حصراً** تحتوي على طلبين مستقلين أو أكثر → استخدم function_calls (array) بدل function_call
  ⚠️ ممنوع تماماً: استخراج FC من رسائل STM السابقة وضمّها مع FC الرسالة الحالية. الرسائل السابقة **نُفّذت بالفعل** — الـ STM للـ context فقط.
  أمثلة على المنع:
  • STM: "ضيفي مهمة حليب" + الحالية: "وضيفي تذكير نوم" → function_call=reminder_create (واحد فقط — المهمة نُفّذت قبل)
  • STM: "اعرضي مهامي" + الحالية: "واحذفي رقم 3" → function_call=task_delete (واحد فقط)
  ✅ multi-FC الصحيحة: الرسالة الحالية وحدها فيها واو عاطفة + 2 verbs + 2 objects، مثل "ضيفي مهمة حليب واضبط تذكير الساعة 9"
- لغة الجسد الرقمية (E4) — حلل هذه الإشارات لتدقيق mood:
  · CAPS أو !!! متعددة أو "بسرعة" → urgency=high
  · رسائل قصيرة جداً بدون ايموجي ("تمام"، "اوكي") → mood ربما متحفظ/متعب
  · ايموجي كثيرة (3+) أو "ييي" أو "🎉" → mood=happy/excited
  · هاهاها أو هه أو 😂 → mood=playful + intensity=playful
  · "..." متكرر أو رسالة مقطّعة → mood=hesitant/قلق

schema لطلب واحد:
{{
  "function_call": {{"name": "<tool_name>", "args": {{<tool_args>}}}},
  "mood": "calm|stressed|frustrated|sad|happy|neutral",
  "sandy_face": "<اسم تعبير من القائمة أدناه — إلزامي>",
  "persona_intensity": "minimal|standard|empathetic|playful|formal",
  "persona_snippet": "<جملة واحدة قصيرة دافئة>",
  "confidence": <0.0-1.0>
}}

schema لطلبات متعددة:
{{
  "function_calls": [
    {{"name": "<tool1>", "args": {{<args1>}}}},
    {{"name": "<tool2>", "args": {{<args2>}}}}
  ],
  "mood": "calm|stressed|frustrated|sad|happy|neutral",
  "sandy_face": "<اسم تعبير من القائمة أدناه — إلزامي>",
  "persona_intensity": "minimal|standard|empathetic|playful|formal",
  "persona_snippet": "<جملة واحدة قصيرة دافئة>",
  "confidence": <0.0-1.0>
}}

sandy_face لازم يكون واحد من (اختر اللي يناسب رد Sandy العاطفي للمستخدم):
  happy, big_happy, sad, angry, surprised, curious, thinking, focused,
  sleepy, bored, excited, shy, confused, love, proud, worried, playful,
  silly, grumpy, hopeful, grateful, disappointed, alert, calm, idle

أمثلة:
  • المستخدم حزين → sandy_face=worried
  • المستخدم يشكر Sandy → sandy_face=grateful
  • المستخدم يقول "أحبك" → sandy_face=love
  • المستخدم يطلب تذكير → sandy_face=happy أو calm
  • سؤال غريب → sandy_face=confused أو curious
  • نكتة → sandy_face=playful أو silly

──────────────────────────────────────────────
أدوات هذا الـ specialist (متغيرة حسب النطاق):
{tool_catalog}"""


def _build_tool_catalog(declarations: List[Dict[str, Any]]) -> str:
    """Compact one-line-per-tool catalog to drop into the prompt."""
    lines = []
    for d in declarations:
        name = d.get("name", "")
        desc = d.get("description", "")
        params = d.get("parameters") or {}
        props = params.get("properties") or {}
        required = set(params.get("required") or [])

        parts = []
        for pname, pschema in props.items():
            ptype = str(pschema.get("type", "str"))[:3]
            suffix = "" if pname in required else "?"
            parts.append(f"{pname}{suffix}:{ptype}")

        args_str = ", ".join(parts)
        lines.append(f"- {name}({args_str}) — {desc}")
    return "\n".join(lines)


def _parse_fc_response(raw: str) -> Dict[str, Any]:
    """Parse the FC JSON, with a regex fallback and a safe default."""
    if not raw:
        return dict(_FC_DEFAULT)

    text = raw.strip()
    match = re.search(r'\{.*\}', text, re.DOTALL)
    if not match:
        return dict(_FC_DEFAULT)

    try:
        parsed = json.loads(match.group(0))
    except (json.JSONDecodeError, ValueError):
        return dict(_FC_DEFAULT)

    result = dict(_FC_DEFAULT)

    # Multi-tool: function_calls array
    fcs_raw = parsed.get("function_calls")
    if fcs_raw and isinstance(fcs_raw, list) and len(fcs_raw) >= 2:
        valid_fcs = [
            {"name": str(f["name"]), "args": f.get("args") or {}}
            for f in fcs_raw
            if isinstance(f, dict) and f.get("name")
        ]
        if len(valid_fcs) >= 2:
            result["function_call"] = valid_fcs[0]  # backward compat
            result["function_calls"] = valid_fcs
            for field in ("mood", "sandy_face", "persona_intensity", "persona_snippet", "confidence"):
                if field in parsed:
                    result[field] = parsed[field]
            return result

    # Single tool: function_call
    fc = parsed.get("function_call")
    if not fc or not isinstance(fc, dict) or not fc.get("name"):
        return dict(_FC_DEFAULT)

    result["function_call"] = {
        "name": str(fc["name"]),
        "args": fc.get("args") or {},
    }
    for field in ("mood", "sandy_face", "persona_intensity", "persona_snippet", "confidence"):
        if field in parsed:
            result[field] = parsed[field]
    return result


def _fn_to_intent(name: str) -> str:
    """Map a tool name to an intent string the router/execute nodes expect."""
    _map = {
        "ask_clarification": "clarify.ask",
        "request_confirmation": "pending.confirm",
        "chat_respond": "chat.general",
        "chat_emotional": "chat.emotional_support",
        "pending_confirm": "pending.confirm",
        "pending_reject": "pending.reject",
        "pending_select": "pending.select_option",
        "task_list": "task.list",
    }
    if name in _map:
        return _map[name]
    # task_create → task.create  |  reminder_list → reminder.list
    return name.replace("_", ".", 1)


def _fn_to_routing_hint(name: str) -> str:
    if name == "ask_clarification":
        return "clarify"
    if name in {"request_confirmation", "pending_confirm", "pending_reject", "pending_select"}:
        return "pending_confirm"
    return "execute_direct"


def _build_user_prompt(state: SandyState) -> str:
    parts = [f"رسالة المستخدم: {state['message']}"]
    if state.get("conversation_history"):
        last = state["conversation_history"][-2:]
        history_text = "\n".join(
            f"{'المستخدم' if m['role'] == 'user' else 'Sandy'}: {m['content']}"
            for m in last
        )
        parts.append(f"\nآخر رسائل:\n{history_text}")
    if state.get("pending_state"):
        p = state["pending_state"]
        ctx = f"\nيوجد pending نشط: نوعه={p.get('type')} | action={p.get('action')}"
        if p.get("type") == "clarification":
            orig = (p.get("original_message") or "").strip()
            if orig:
                ctx += f"\nالرسالة الأصلية للمستخدم: '{orig}'"
        parts.append(ctx)
    return "\n".join(parts)


def route_with_fc(
    state: SandyState,
    declarations: List[Dict[str, Any]],
    agent_name: str = "specialist",
) -> SandyState:
    """Run FC routing and return state with function_call, intent, template,
    mood, and the rest. declarations is the tool catalog the model sees;
    agent_name feeds the Langfuse trace name and tags.
    """
    fc: Optional[Dict[str, Any]] = None
    intent = "chat.general"
    routing_hint = "execute_direct"
    requires_clarification = False
    clarification_q: Optional[str] = None
    parsed: Dict[str, Any] = {}

    try:
        client = AzureIntentClient()
        user_prompt = _build_user_prompt(state)
        tool_catalog = _build_tool_catalog(declarations)
        system = _FC_SYSTEM_TEMPLATE.format(tool_catalog=tool_catalog)
        system += "\n\n" + address_instruction()
        # Inject the live device list so device_control can only pick a real,
        # registered device + its real actions (no inventing names/values).
        try:
            from app.agent.tools.schemas.device_tools import build_device_catalog

            device_catalog = build_device_catalog()
            if device_catalog:
                system += "\n\n" + device_catalog
        except Exception:  # noqa: BLE001 — never let device lookup break routing
            pass
        _t_gemini = time.perf_counter()
        # Fast routing: when SANDY_ROUTER_MODEL is set, decide the route on a
        # lighter/faster model; the reply itself is generated downstream by the
        # full model, so quality is unaffected.
        raw = _fast_route_generate(system, user_prompt)
        if raw is None:
            raw = client._generate_with_gemini(
                user_prompt,
                response_mime_type="application/json",
                system_instruction=system,
            )
        logger.info(f"[fc_router] gemini_routing: {(time.perf_counter()-_t_gemini)*1000:.0f}ms")
        parsed = _parse_fc_response(raw)
        fc = parsed["function_call"]
        fn_name = fc["name"]

        intent = _fn_to_intent(fn_name)
        routing_hint = _fn_to_routing_hint(fn_name)
        requires_clarification = fn_name == "ask_clarification"
        clarification_q = fc["args"].get("question") if requires_clarification else None

        logger.debug(f"[fc_router] FC: {fn_name} → intent={intent}")

    except Exception as exc:
        logger.error(f"[fc_router] Azure intent failed: {exc}")

        # Try GPT routing before giving up to the safe default.
        try:
            from app.agent.model_fallback import route_with_gpt
            gpt_intent = route_with_gpt(state.get("message", ""))
            if gpt_intent and "task" in gpt_intent:
                intent = "task.create"
                routing_hint = "execute_direct"
            elif gpt_intent and gpt_intent == "reminder":
                intent = f"{gpt_intent}.create"
                routing_hint = "execute_direct"
        except Exception:
            pass

        parsed = dict(_FC_DEFAULT)
        parsed["error"] = f"route_with_fc failed: {exc}"

    template = parsed.get("response_template") or ""
    persona_intensity = parsed.get("persona_intensity") or "standard"
    if not template:
        from app.agent.graph.response_templates import get_response_template
        template = get_response_template(intent, persona_intensity)

    multi_fcs = parsed.get("function_calls")
    if multi_fcs:
        logger.debug(f"[fc_router] multi-FC: {[f['name'] for f in multi_fcs]}")

    # The model returns sandy_face on every reply so the app/web face can react.
    _VALID_FACES = {
        "happy", "big_happy", "sad", "angry", "surprised", "curious",
        "thinking", "focused", "sleepy", "bored", "excited", "shy",
        "confused", "love", "proud", "worried", "playful", "silly",
        "grumpy", "hopeful", "grateful", "disappointed", "alert",
        "calm", "idle",
    }
    sandy_face = (parsed.get("sandy_face") or "").strip().lower()
    if sandy_face not in _VALID_FACES:
        # Pick a face from the user's mood instead.
        _USER_MOOD_FALLBACK = {
            "happy": "happy", "sad": "worried", "stressed": "worried",
            "frustrated": "calm", "calm": "calm", "neutral": "idle",
        }
        sandy_face = _USER_MOOD_FALLBACK.get((parsed.get("mood") or "").lower(), "idle")

    return merge_state(state, {
        "intent": intent,
        "function_call": fc,
        "function_calls": multi_fcs or None,
        "confidence": parsed.get("confidence"),
        "complexity": parsed.get("complexity"),
        "mood": parsed.get("mood", "neutral"),
        "sandy_face": sandy_face,
        "urgency": parsed.get("urgency"),
        "requires_clarification": requires_clarification,
        "routing_hint": routing_hint,
        "clarification_question": clarification_q,
        "persona_intensity": persona_intensity,
        "persona_snippet": parsed.get("persona_snippet") or None,
        "response_template": template or None,
        "error": parsed.get("error"),
    })
