#!/usr/bin/env python3
"""Write the TLS root certificates the Arduino boards trust.

The camera (vision-core) and the room node used ``setInsecure()``: an encrypted
channel to whoever answers. On a hostile Wi-Fi that is anyone — and the camera
posts pictures of the owner's home, and the room node obeys whatever the
"broker" tells it to switch.

Now both verify the server against a short list of roots:

- ISRG Root X1 / X2 — Let's Encrypt, which the MQTT broker uses.
- DigiCert Global Root G2 / G3 — ``*.herokuapp.com`` (Heroku moved to G2).
- Amazon Root CA 1 — in case the app moves behind AWS certificates.

More than one root per service on purpose: a board in a customer's house cannot
be re-flashed the day a provider switches issuer, so the list covers the obvious
next step too. The roots expire 2035–2040.

    python3 scripts/gen_ca_roots.py      # rewrites both sandy_ca_roots.h
"""
from __future__ import annotations

import pathlib
import re

import certifi

ROOT = pathlib.Path(__file__).resolve().parents[1]
TARGETS = [ROOT / "vision-core" / "sandy_ca_roots.h",
           ROOT / "room-node" / "sandy_ca_roots.h"]
WANTED = ["ISRG Root X1", "ISRG Root X2", "DigiCert Global Root G2",
          "DigiCert Global Root G3", "Amazon Root CA 1"]


def _bundle() -> dict:
    text = pathlib.Path(certifi.where()).read_text()
    out = {}
    for m in re.finditer(r"# Label: \"([^\"]+)\".*?(-----BEGIN CERTIFICATE-----.*?"
                         r"-----END CERTIFICATE-----)", text, re.S):
        out[m.group(1)] = m.group(2).strip()
    return out


def render() -> str:
    certs = _bundle()
    missing = [n for n in WANTED if n not in certs]
    if missing:
        raise SystemExit(f"not in the CA bundle: {missing}")
    lines = [
        "// Generated by scripts/gen_ca_roots.py — do not edit by hand.",
        "// The roots this board trusts for the broker and the server (why: see",
        "// the script). Passed to WiFiClientSecure::setCACert().",
        "#pragma once",
        "",
        "static const char SANDY_CA_ROOTS[] =",
    ]
    for name in WANTED:
        lines.append(f"  // {name}")
        for row in certs[name].splitlines():
            lines.append(f'  "{row}\\n"')
    lines[-1] += ";"
    return "\n".join(lines) + "\n"


def main() -> None:
    body = render()
    for t in TARGETS:
        t.write_text(body)
        print(f"wrote {t.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
