#!/usr/bin/env python3
"""Generate firmware/brain-core/HARDWARE.md from the code that decides what the robot does.

The document this replaces was written by hand and went stale in five places
within a month: it claimed twenty-six moods where there were twenty-five, said
the microphone gain was fixed in firmware after it had become a slider in the
app, and listed the buzzer's flag as on while it was off. It was quoted as a
source in a readiness report — including by me — and the quote was wrong.

The failure was not carelessness. A hand-written inventory of a system that
changes weekly is a second copy of the truth, and second copies drift. So this
one is not written; it is derived, from the three files that genuinely decide:

  1. firmware/.../config.h          — which subsystems are compiled in, and pins
  2. firmware/.../sandy_mqtt.c      — the outputs the board declares to the cloud
  3. cloud/.../node_provision.py    — how each output is presented in the app

A test regenerates this and fails if the committed file differs, so the document
cannot fall behind the code without turning CI red. That is the whole point:
drift becomes a build failure instead of a discovery six weeks later.

Usage:  python3 scripts/gen_hardware_doc.py          # write the doc
        python3 scripts/gen_hardware_doc.py --check  # exit 1 if it is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_H = ROOT / "firmware/brain-core/main/include/config.h"
MQTT_C = ROOT / "firmware/brain-core/main/sandy_mqtt.c"
PROVISION_PY = ROOT / "cloud/app/features/node_provision.py"
OUT = ROOT / "firmware/brain-core/HARDWARE.md"


def read_flags() -> list[tuple[str, bool, str]]:
    """(name, enabled, trailing comment) for every ENABLE_* in config.h."""
    out = []
    for line in CONFIG_H.read_text(encoding="utf-8").splitlines():
        m = re.match(r"#define\s+(ENABLE_\w+)\s+(\d+)\s*(?://\s*(.*))?", line)
        if m:
            out.append((m.group(1), m.group(2) == "1", (m.group(3) or "").strip()))
    return out


def read_pins() -> list[tuple[str, str]]:
    out = []
    for line in CONFIG_H.read_text(encoding="utf-8").splitlines():
        m = re.match(r"#define\s+(PIN_\w+)\s+(\d+)", line)
        if m:
            out.append((m.group(1), m.group(2)))
    return out


def read_define(name: str) -> str:
    m = re.search(rf'#define\s+{name}\s+"([^"]*)"', CONFIG_H.read_text(encoding="utf-8"))
    return m.group(1) if m else "?"


def read_outputs() -> list[tuple[str, str]]:
    """The (id, kind) pairs the firmware puts in every heartbeat."""
    src = MQTT_C.read_text(encoding="utf-8")
    block = src[src.index("OUTPUTS_JSON ="):]
    block = block[: block.index('"]";')]
    return re.findall(r'\\"id\\":\\"(\w+)\\",\\"kind\\":\\"(\w+)\\"', block)


def read_catalogue() -> dict[str, dict]:
    """PART_CATALOGUE, read by executing only the module's own literals.

    Imported rather than parsed: the file is plain data and importing it means
    this cannot disagree with what the backend actually serves.
    """
    sys.path.insert(0, str(ROOT / "cloud"))
    from app.features.node_provision import PART_CATALOGUE  # noqa: PLC0415
    return PART_CATALOGUE


def build() -> str:
    flags = read_flags()
    outputs = read_outputs()
    catalogue = read_catalogue()

    lines: list[str] = []
    add = lines.append

    add("# Sandy — what the robot can actually do")
    add("")
    add("<!-- GENERATED by scripts/gen_hardware_doc.py — do not edit by hand. -->")
    add("<!-- A test fails if this file and the code disagree. Run the script. -->")
    add("")
    add(f"Board `{read_define('SANDY_BOARD_ID')}`, "
        f"firmware `{read_define('SANDY_FW_VERSION')}`.")
    add("")
    add("Three files decide everything below, and this is derived from all three:")
    add("`config.h` compiles a subsystem in or leaves it out, `sandy_mqtt.c` "
        "declares what the board offers, and `node_provision.py` turns each "
        "offer into a control in the app.")
    add("")

    add("## Compiled in")
    add("")
    add("A subsystem set to 0 is not present in the binary. It is not broken and "
        "not hidden — the code is not there, so nothing can reach it until the "
        "flag is turned on and the board is reflashed.")
    add("")
    add("| Subsystem | State | Note |")
    add("|---|---|---|")
    for name, on, note in flags:
        add(f"| `{name}` | {'on' if on else 'off'} | {note or ''} |")
    add("")

    add("## Reachable from the app")
    add("")
    add("Every row here was declared by the board itself in a heartbeat and "
        "matched to a control by the catalogue. Nothing appears in the app that "
        "the hardware did not first say it had.")
    add("")
    add("| Output | Kind | Shows up as | Control | Values |")
    add("|---|---|---|---|---|")
    for oid, kind in outputs:
        spec = catalogue.get(oid)
        if spec is None:
            add(f"| `{oid}` | {kind} | — | **no catalogue entry** | "
                "declared by the board, not presented |")
            continue
        meta = spec.get("meta", {})
        if "values" in meta:
            vals = meta["values"]
            shown = ", ".join(f"`{v}`" for v in vals[:6])
            if len(vals) > 6:
                shown += f" … ({len(vals)} total)"
        elif "min" in meta:
            shown = f"{meta['min']}–{meta['max']}"
        else:
            shown = "on / off"
        add(f"| `{oid}` | {kind} | {spec['label']} | {spec['control_type']} | {shown} |")
    add("")

    orphans = [k for k in catalogue if k not in {o for o, _ in outputs}]
    if orphans:
        add("### Presented but not declared")
        add("")
        add("The catalogue knows how to show these; no board has offered one. "
            "Either a part that is not fitted, or firmware older than the entry.")
        add("")
        for k in orphans:
            add(f"- `{k}` — {catalogue[k]['label']}")
        add("")

    add("## Pins")
    add("")
    add("Wiring, and what happens if two things claim one pin, is in "
        "`firmware/brain-core/WIRING.md`. This is only the assignment.")
    add("")
    add("| Signal | GPIO |")
    add("|---|---|")
    for name, pin in read_pins():
        add(f"| `{name}` | {pin} |")
    add("")

    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed file is out of date")
    args = ap.parse_args()

    fresh = build()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != fresh:
            print("firmware/brain-core/HARDWARE.md is out of date — run scripts/gen_hardware_doc.py")
            return 1
        print("firmware/brain-core/HARDWARE.md is current")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(fresh, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
