#ifndef SANDY_ESP32CAM_SECRETS_H
#define SANDY_ESP32CAM_SECRETS_H

// WiFi
#define SECRET_SSID "YOUR_WIFI_SSID"
#define SECRET_OPTIONAL_PASS "YOUR_WIFI_PASSWORD"

// MQTT (HiveMQ Cloud) — نفس الـ broker تبع Sandy
#define SANDY_MQTT_HOST "YOUR_HIVEMQ_HOST.s1.eu.hivemq.cloud"
#define SANDY_MQTT_PORT 8883
#define SANDY_MQTT_USER "YOUR_MQTT_USER"
#define SANDY_MQTT_PASS "YOUR_MQTT_PASSWORD"

// OTA
#define SANDY_OTA_PASSWORD "YOUR_OTA_PASSWORD"

#endif
